title: Blog Iqbal
description: >-
  Blog developer tentang development dari developer yang lebih
  terbiasa menulis instruksi untuk mesin semi canggih.
baseurl: ""
url: ""

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed